---
write_registers:
  name: Write Registers
  description: >
    Writes one or more registers
  fields:
    friendly_name:
      name: Friendly Name
      description: Unique friendly name
      example: "inverter_name"
      default: "inverter_name"
      selector:
        text:
    start_address:
      name: Start Address
      description: Start address to write to
      required: true
      example: 41001
      default: 1
      selector:
        number:
          mode: box
    values:
      name: Values
      description: Comma seperated list of values to write
      required: true
      example: "1, 2, 3"
      default: "1, 2, 3"
      selector:
        text:
